new debian directory

diff --git a/debian/tox-bootstrapd.postinst b/debian/tox-bootstrapd.postinst
--- a/debian/tox-bootstrapd.postinst
+++ b/debian/tox-bootstrapd.postinst
@@ -1,42 +1,46 @@
 #!/bin/sh
+# postinst script for tox-bootstrapd
+#
+# see: dh_installdeb(1)
 
 set -e
 
-TOXUSER=tox-bootstrapd
-TOXHOME=/var/lib/${TOXUSER}
-COMMENT="Tox Bootstrap Daemon"
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
 case "$1" in
-    configure|reconfigure)
+	configure)
+		if ! getent passwd tox-bootstrapd > /dev/null 2>&1 ; then
+			useradd -c "Account to run Tox's DHT bootstrap daemon" -r -d /var/lib/tox-bootstrapd -m -s /sbin/nologin -U tox-bootstrapd
+			chmod 700 /var/lib/tox-bootstrapd
+		fi
 
-    # Older versions of adduser created the home directory.
-    # The version of adduser in Debian unstable does not.
-    [ -d ${TOXHOME} ] || mkdir -m0750 ${TOXHOME}
+		if [ -x /etc/init.d/tox-bootstrapd ]; then
+			update-rc.d tox-bootstrapd defaults
+			invoke-rc.d tox-bootstrapd start
+		fi
+	;;
 
-    # Create user and group as a system user.
-    if getent passwd ${TOXUSER} > /dev/null 2>&1 ; then
-        groupadd -f ${TOXUSER} || true
-        usermod -c "${COMMENT}" -d ${TOXHOME} -g ${TOXUSER} -s "/bin/false" \
-            ${TOXUSER} -e 1 > /dev/null 2>&1 || true
-    else
-        adduser --system --quiet --group --gecos "${COMMENT}" --home ${TOXHOME} ${TOXUSER} > /dev/null 2>&1
-    fi
+	abort-upgrade|abort-remove|abort-deconfigure)
+	;;
 
-    chown -f -R ${TOXUSER}:${TOXUSER} ${TOXHOME}
-    chmod 700 ${TOXHOME}
-    setcap cap_net_bind_service=+ep /usr/sbin/tox-bootstrapd
-    #setcap cap_net_bind_service=+ep /usr/sbin/tox-DHT_bootstrap
-
-;;
-abort-upgrade|abort-remove|abort-deconfigure)
-    echo "Aborting upgrade"
-    exit 0
-    ;;
-*)
-        echo "postinst called with unknown argument \`$1'" >&2
-                exit 0
-                ;;
+	*)
+		echo "postinst called with unknown argument \`$1'" >&2
+		exit 1
+	;;
 esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
